/* ex: set ro ft=c: -*- buffer-read-only: t -*-
 *
 * !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 * This file is auto-generated by Unicode::Towctrans 0.01
 * mkheader
 * for Unicode 18.0.0
 * Any changes here will be lost!
 */
/*
Copyright Â© 2005-2014 Rich Felker, et al.
Copyright Â© 2018,2020,2026 Reini Urban

------------------------------------------------------------------
musl as a whole is licensed under the following standard MIT license:
---------------------------------------------------------------------

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
----------------------------------------------------------------------
*/

#include <stdint.h>
#include <assert.h>

/* map from upper until upper, to lower */
#define CASEMAP(u1, u2, l) \
    { (u1), (l) - (u1), (u2) - (u1) + 1 }
/* map from upper until lower, with dist 1 */
#define CASELACE(u1, u2) CASEMAP((u1), (u2), (u1) + 1)

/* Unicode 18.0.0 */

static const struct {
    unsigned short upper; /* base */
    signed char lower; /* distance from upper to lower */
    unsigned char len; /* how many */
} casemaps[] = {
    /* from, until, to */
    CASEMAP(0x0042, 0x0062, 0x005a),	/* 'B' -> 'b' .. 'Z' */
    CASEMAP(0x00c1, 0x00e1, 0x00d6),	/* 'Á' -> 'á' .. 'Ö' */
    CASEMAP(0x00d9, 0x00f9, 0x00de),	/* 'Ù' -> 'ù' .. 'Þ' */
    CASELACE(0x014a, 0x014b),		/* 'Ɗ' -> 'ɗ' */
    CASELACE(0x0179, 0x017a),		/* 'Ɗ' -> 'ɗ' */
    CASELACE(0x0182, 0x0183),		/* 'Ɗ' -> 'ɗ' */
    CASELACE(0x0187, 0x0188),		/* 'Ɗ' -> 'ɗ' */
    CASEMAP(0x018a, 0x0257, 0x018a),	/* 'Ɗ' -> 'ɗ' .. 'Ɗ' */
    CASELACE(0x018b, 0x018c),		/* 'Ə' -> 'ə' */
    CASEMAP(0x018f, 0x0259, 0x018f),	/* 'Ə' -> 'ə' .. 'Ə' */
    CASEMAP(0x0190, 0x025b, 0x0190),	/* 'Ɛ' -> 'ɛ' .. 'Ɛ' */
    CASELACE(0x0191, 0x0192),		/* 'Ɣ' -> 'ɣ' */
    CASEMAP(0x0194, 0x0263, 0x0194),	/* 'Ɣ' -> 'ɣ' .. 'Ɣ' */
    CASEMAP(0x0197, 0x0268, 0x0197),	/* 'Ɨ' -> 'ɨ' .. 'Ɨ' */
    CASELACE(0x0198, 0x0199),		/* 'Ɲ' -> 'ɲ' */
    CASEMAP(0x019d, 0x0272, 0x019d),	/* 'Ɲ' -> 'ɲ' .. 'Ɲ' */
    CASELACE(0x01a0, 0x01a1),		/* 'Ʋ' -> 'ʋ' */
    CASELACE(0x01a7, 0x01a8),		/* 'Ʋ' -> 'ʋ' */
    CASELACE(0x01af, 0x01b0),		/* 'Ʋ' -> 'ʋ' */
    CASEMAP(0x01b2, 0x028b, 0x01b2),	/* 'Ʋ' -> 'ʋ' .. 'Ʋ' */
    CASELACE(0x01b3, 0x01b4),		/* 'Ǳ' -> 'ǳ' */
    CASELACE(0x01b8, 0x01b9),		/* 'Ǳ' -> 'ǳ' */
    CASELACE(0x01c5, 0x01c6),		/* 'Ǳ' -> 'ǳ' */
    CASELACE(0x01c8, 0x01c9),		/* 'Ǳ' -> 'ǳ' */
    CASELACE(0x01cb, 0x01cc),		/* 'Ǳ' -> 'ǳ' */
    CASEMAP(0x01f1, 0x01f3, 0x01f1),	/* 'Ǳ' -> 'ǳ' .. 'Ǳ' */
    CASELACE(0x01f2, 0x01f3),		/* 'Ƿ' -> 'ƿ' */
    CASEMAP(0x01f7, 0x01bf, 0x01f7),	/* 'Ƿ' -> 'ƿ' .. 'Ƿ' */
    CASELACE(0x01f8, 0x01f9),		/* 'Ⱦ' -> 'ⱦ' */
    CASELACE(0x023b, 0x023c),		/* 'Ⱦ' -> 'ⱦ' */
    CASEMAP(0x023e, 0x2c66, 0x023e),	/* 'Ⱦ' -> 'ⱦ' .. 'Ⱦ' */
    CASEMAP(0x0244, 0x0289, 0x0244),	/* 'Ʉ' -> 'ʉ' .. 'Ʉ' */
    CASEMAP(0x0245, 0x028c, 0x0245),	/* 'Ʌ' -> 'ʌ' .. 'Ʌ' */
    CASELACE(0x0246, 0x0247),		/* 'Ή' -> 'ή' */
    CASEMAP(0x0389, 0x03ae, 0x038a),	/* 'Ή' -> 'ή' .. 'Ί' */
    CASEMAP(0x038f, 0x03ce, 0x038f),	/* 'Ώ' -> 'ώ' .. 'Ώ' */
    CASEMAP(0x0391, 0x03b1, 0x03a1),	/* 'Α' -> 'α' .. 'Ρ' */
    CASEMAP(0x03a4, 0x03c4, 0x03ab),	/* 'Τ' -> 'τ' .. 'Ϋ' */
    CASEMAP(0x03d0, 0x03b2, 0x03d0),	/* 'ϐ' -> 'β' .. 'ϐ' */
    CASEMAP(0x03d1, 0x03b8, 0x03d1),	/* 'ϑ' -> 'θ' .. 'ϑ' */
    CASEMAP(0x03d6, 0x03c0, 0x03d6),	/* 'ϖ' -> 'π' .. 'ϖ' */
    CASEMAP(0x03f1, 0x03c1, 0x03f1),	/* 'ϱ' -> 'ρ' .. 'ϱ' */
    CASEMAP(0x03f5, 0x03b5, 0x03f5),	/* 'ϵ' -> 'ε' .. 'ϵ' */
    CASELACE(0x03fa, 0x03fb),		/* 'Ͼ' -> 'ͼ' */
    CASEMAP(0x03fe, 0x037c, 0x03ff),	/* 'Ͼ' -> 'ͼ' .. 'Ͽ' */
    CASEMAP(0x0400, 0x0450, 0x040f),	/* 'Ѐ' -> 'ѐ' .. 'Џ' */
    CASEMAP(0x0410, 0x0430, 0x042f),	/* 'А' -> 'а' .. 'Я' */
    CASELACE(0x04c1, 0x04c2),		/* 'Բ' -> 'բ' */
    CASEMAP(0x0532, 0x0562, 0x0556),	/* 'Բ' -> 'բ' .. 'Ֆ' */
    CASEMAP(0x10a1, 0x2d01, 0x10c5),	/* 'Ⴁ' -> 'ⴁ' .. 'Ⴥ' */
    CASEMAP(0x13f9, 0x13f1, 0x13fd),	/* 'ᏹ' -> 'Ᏹ' .. 'ᏽ' */
    CASEMAP(0x1c81, 0x0434, 0x1c81),	/* 'ᲁ' -> 'д' .. 'ᲁ' */
    CASEMAP(0x1c82, 0x043e, 0x1c82),	/* 'ᲂ' -> 'о' .. 'ᲂ' */
    CASEMAP(0x1c83, 0x0441, 0x1c84),	/* 'ᲃ' -> 'с' .. 'ᲄ' */
    CASEMAP(0x1c85, 0x0442, 0x1c85),	/* 'ᲅ' -> 'т' .. 'ᲅ' */
    CASEMAP(0x1c86, 0x044a, 0x1c86),	/* 'ᲆ' -> 'ъ' .. 'ᲆ' */
    CASEMAP(0x1c87, 0x0463, 0x1c87),	/* 'ᲇ' -> 'ѣ' .. 'ᲇ' */
    CASEMAP(0x1c88, 0xa64b, 0x1c88),	/* 'ᲈ' -> 'ꙋ' .. 'ᲈ' */
    CASELACE(0x1c89, 0x1c8a),		/* 'Ბ' -> 'ბ' */
    CASEMAP(0x1c91, 0x10d1, 0x1cba),	/* 'Ბ' -> 'ბ' .. 'Ჺ' */
    CASEMAP(0x1cbe, 0x10fe, 0x1cbf),	/* 'Ჾ' -> 'ჾ' .. 'Ჿ' */
    CASEMAP(0x1e9b, 0x1e61, 0x1e9b),	/* 'ẛ' -> 'ṡ' .. 'ẛ' */
    CASEMAP(0x1f09, 0x1f01, 0x1f0f),	/* 'Ἁ' -> 'ἁ' .. 'Ἇ' */
    CASEMAP(0x1f19, 0x1f11, 0x1f1d),	/* 'Ἑ' -> 'ἑ' .. 'Ἕ' */
    CASEMAP(0x1f29, 0x1f21, 0x1f2f),	/* 'Ἡ' -> 'ἡ' .. 'Ἧ' */
    CASEMAP(0x1f39, 0x1f31, 0x1f3f),	/* 'Ἱ' -> 'ἱ' .. 'Ἷ' */
    CASEMAP(0x1f49, 0x1f41, 0x1f4d),	/* 'Ὁ' -> 'ὁ' .. 'Ὅ' */
    CASEMAP(0x1f69, 0x1f61, 0x1f6f),	/* 'Ὡ' -> 'ὡ' .. 'Ὧ' */
    CASEMAP(0x1fb8, 0x1fb0, 0x1fb9),	/* 'Ᾰ' -> 'ᾰ' .. 'Ᾱ' */
    CASEMAP(0x1fba, 0x1f70, 0x1fbb),	/* 'Ὰ' -> 'ὰ' .. 'Ά' */
    CASEMAP(0x1fc8, 0x1f72, 0x1fcb),	/* 'Ὲ' -> 'ὲ' .. 'Ή' */
    CASEMAP(0x1fd8, 0x1fd0, 0x1fd9),	/* 'Ῐ' -> 'ῐ' .. 'Ῑ' */
    CASEMAP(0x1fda, 0x1f76, 0x1fdb),	/* 'Ὶ' -> 'ὶ' .. 'Ί' */
    CASEMAP(0x1fe8, 0x1fe0, 0x1fe9),	/* 'Ῠ' -> 'ῠ' .. 'Ῡ' */
    CASEMAP(0x1fea, 0x1f7a, 0x1feb),	/* 'Ὺ' -> 'ὺ' .. 'Ύ' */
    CASEMAP(0x1fec, 0x1fe5, 0x1fec),	/* 'Ῥ' -> 'ῥ' .. 'Ῥ' */
    CASEMAP(0x1ff8, 0x1f78, 0x1ff9),	/* 'Ὸ' -> 'ὸ' .. 'Ό' */
    CASEMAP(0x1ffa, 0x1f7c, 0x1ffb),	/* 'Ὼ' -> 'ὼ' .. 'Ώ' */
    CASEMAP(0x212b, 0x00e5, 0x212b),	/* 'Å' -> 'å' .. 'Å' */
    CASEMAP(0x2161, 0x2171, 0x216f),	/* 'Ⅱ' -> 'ⅱ' .. 'Ⅿ' */
    CASEMAP(0x24b7, 0x24d1, 0x24cf),	/* 'Ⓑ' -> 'ⓑ' .. 'Ⓩ' */
    CASEMAP(0x2c01, 0x2c31, 0x2c2f),	/* 'Ⰱ' -> 'ⰱ' .. 'Ⱟ' */
    CASEMAP(0x2c63, 0x1d7d, 0x2c63),	/* 'Ᵽ' -> 'ᵽ' .. 'Ᵽ' */
    CASEMAP(0x2c64, 0x027d, 0x2c64),	/* 'Ɽ' -> 'ɽ' .. 'Ɽ' */
    CASEMAP(0x2c6e, 0x0271, 0x2c6e),	/* 'Ɱ' -> 'ɱ' .. 'Ɱ' */
    CASEMAP(0x2c6f, 0x0250, 0x2c6f),	/* 'Ɐ' -> 'ɐ' .. 'Ɐ' */
    CASEMAP(0x2c70, 0x0252, 0x2c70),	/* 'Ɒ' -> 'ɒ' .. 'Ɒ' */
    CASEMAP(0x2c7f, 0x0240, 0x2c7f),	/* 'Ɀ' -> 'ɀ' .. 'Ɀ' */
    CASELACE(0x2c80, 0x2c81),		/* 'Ɜ' -> 'ɜ' */
    CASELACE(0xa77e, 0xa77f),		/* 'Ɜ' -> 'ɜ' */
    CASEMAP(0xa7ab, 0x025c, 0xa7ab),	/* 'Ɜ' -> 'ɜ' .. 'Ɜ' */
    CASEMAP(0xa7ac, 0x0261, 0xa7ac),	/* 'Ɡ' -> 'ɡ' .. 'Ɡ' */
    CASEMAP(0xa7ad, 0x026c, 0xa7ad),	/* 'Ɬ' -> 'ɬ' .. 'Ɬ' */
    CASEMAP(0xa7ae, 0x026a, 0xa7ae),	/* 'Ɪ' -> 'ɪ' .. 'Ɪ' */
    CASEMAP(0xa7b1, 0x0287, 0xa7b1),	/* 'Ʇ' -> 'ʇ' .. 'Ʇ' */
    CASEMAP(0xa7b2, 0x029d, 0xa7b2),	/* 'Ʝ' -> 'ʝ' .. 'Ʝ' */
    CASEMAP(0xa7b3, 0xab53, 0xa7b3),	/* 'Ꭓ' -> 'ꭓ' .. 'Ꭓ' */
    CASELACE(0xa7b4, 0xa7b5),		/* 'Ʂ' -> 'ʂ' */
    CASEMAP(0xa7c5, 0x0282, 0xa7c5),	/* 'Ʂ' -> 'ʂ' .. 'Ʂ' */
    CASEMAP(0xa7c6, 0x1d8e, 0xa7c6),	/* 'Ᶎ' -> 'ᶎ' .. 'Ᶎ' */
    CASELACE(0xa7c7, 0xa7c8),		/* '꟝' -> 'ɷ' */
    CASELACE(0xa7cc, 0xa7cd),		/* '꟝' -> 'ɷ' */
    CASEMAP(0xa7dd, 0x0277, 0xa7dd),	/* '꟝' -> 'ɷ' .. '꟝' */
    CASEMAP(0xab6d, 0xab4c, 0xab6d),	/* '꭭' -> 'ꭌ' .. '꭭' */
    CASEMAP(0xab71, 0x13a1, 0xabbf),	/* 'ꭱ' -> 'Ꭱ' .. 'ꮿ' */
    CASEMAP(0xff22, 0xff42, 0xff3a),	/* 'Ｂ' -> 'ｂ' .. 'Ｚ' */
    {0, 0, 0}};
static const struct {
    unsigned int upper; /* base */
    int lower; /* distance from upper to lower */
    unsigned short len; /* how many */
} casemapsl[] = {
    /* from, until, to */
    CASEMAP(0x10401, 0x10429, 0x10427),	/* '𐐁' -> '𐐩' .. '𐐧' */
    CASEMAP(0x104b1, 0x104d9, 0x104d3),	/* '𐒱' -> '𐓙' .. '𐓓' */
    CASEMAP(0x10571, 0x10598, 0x1057a),	/* '𐕱' -> '𐖘' .. '𐕺' */
    CASEMAP(0x1057d, 0x105a4, 0x1058a),	/* '𐕽' -> '𐖤' .. '𐖊' */
    CASEMAP(0x1058d, 0x105b4, 0x10592),	/* '𐖍' -> '𐖴' .. '𐖒' */
    CASEMAP(0x10595, 0x105bc, 0x10595),	/* '𐖕' -> '𐖼' .. '𐖕' */
    CASEMAP(0x10c81, 0x10cc1, 0x10cb2),	/* '𐲁' -> '𐳁' .. '𐲲' */
    CASEMAP(0x10d51, 0x10d71, 0x10d65),	/* '𐵑' -> '𐵱' .. '𐵥' */
    CASEMAP(0x118a1, 0x118c1, 0x118bf),	/* '𑢡' -> '𑣁' .. '𑢿' */
    CASEMAP(0x16e41, 0x16e61, 0x16e5f),	/* '𖹁' -> '𖹡' .. '𖹟' */
    CASEMAP(0x16ea1, 0x16ebc, 0x16eb8),	/* '𖺡' -> '𖺼' .. '𖺸' */
    CASEMAP(0x1e901, 0x1e923, 0x1e921),	/* '𞤁' -> '𞤣' .. '𞤡' */
    {0, 0, 0}};
static const unsigned short pairs[][2] = {
    {0, 0}};

uint32_t _towcase(uint32_t wc, int lower) {
    int i;
    int lmul = 2 * lower - 1;
    int lmask = lower - 1;
    /* TODO exclusion ranges */
    if (wc <= 0x40)
        return wc;

    for (i = 0; casemaps[i].len; i++) {
        int base = casemaps[i].upper + (lmask & casemaps[i].lower);
        assert(i > 0 ? casemaps[i].upper >= casemaps[i - 1].upper : 1);
        if ((unsigned)wc - base < casemaps[i].len) {
            if (casemaps[i].lower == 1)
                return wc + lower - ((wc - casemaps[i].upper) & 1);
            return wc + lmul * casemaps[i].lower;
        }
        if (lower && casemaps[i].upper > wc)
            break;
    }
    /* TODO */
    for (i = 0; pairs[i][1 - lower]; i++) {
        assert(i > 0 ? pairs[i][0] >= pairs[i - 1][0] : 1);
        if (pairs[i][1 - lower] == wc)
            return pairs[i][lower];
        if (lower && pairs[i][0] > wc)
            break;
    }
    for (i = 0; casemapsl[i].len; i++) {
        unsigned long base = casemapsl[i].upper + (lmask & casemapsl[i].lower);
        assert(i > 0 ? casemapsl[i].upper >= casemapsl[i - 1].upper : 1);
        if ((unsigned)wc - base < casemapsl[i].len) {
            if (casemapsl[i].lower == 1)
                return wc + lower - ((wc - casemapsl[i].upper) & 1);
            return wc + lmul * casemapsl[i].lower;
        }
        if (lower && casemaps[i].upper > wc)
            break;
    }
    return wc;
}
