name: testsuite
permissions: {}

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  ubuntu:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: perl -V
      - run: |
          sudo apt update -y
          sudo apt install -y libperl-dev wget aspell-en libwww-perl perltidy perlimports
      - name: install cpan deps
        uses: perl-actions/install-with-cpm@8b1a9840b26cc3885ae2889749a48629be2501b0 # v1.9
        with:
          install: |
            Test::MinimumVersion::Fast
            Perl::MinimumVersion::Fast
            YAML::Tiny
            File::Find::Rule
            File::Find::Rule::Perl
            Test::CPAN::Meta
            Test::Pod
            Test::Pod::Coverage
            Test::Spelling
            Pod::Spell::CommonMistakes
            Test::CPAN::Changes
            Test::CheckChanges
            Class::XSAccessor
            Text::CSV_XS
            List::MoreUtils
            Test::Kwalitee
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      - run: bin/gen_wctrans
      - run: perl Makefile.PL
      - run: make test || make test TEST_VERBOSE=1
      - run: make -C examples
      - run: make xtest
      - run: make bench

  linux:
    name: "perl ${{ matrix.perl-version }}"
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          [
            "5.42",
            "5.40",
            "5.38",
            "5.36",
            "5.34",
            "5.32",
            "5.30",
            "5.28",
            "5.26",
            "5.24",
            "5.22",
            "5.20",
            "5.18",
            "5.16",
            "5.14",
            "5.12",
          ]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: shogo82148/actions-setup-perl@b6cfc127f1b0a63ac98797800f641494d80f42f8 # v1.37.1
        with:
          perl-version: ${{ matrix.perl-version }}
      - run: perl -V
      - run: sudo apt install -y libperl-dev wget
      - name: install cpan deps
        uses: perl-actions/install-with-cpm@8b1a9840b26cc3885ae2889749a48629be2501b0 # v1.9
        with:
          install: |
            LWP::UserAgent
            LWP::Simple
      - run: bin/gen_wctrans
      - run: perl Makefile.PL
      - run: make test

  macOS:
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: macOS-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: [latest]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: perl -V
      - run: bin/gen_wctrans -v 17
      - run: perl Makefile.PL
      - run: make test || make test TEST_VERBOSE=1

  windows:
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 0
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 0
      VCPKG_DEFAULT_TRIPLET: x64-windows

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: [latest]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: perl -V
      - name: install cpan deps
        uses: perl-actions/install-with-cpm@8b1a9840b26cc3885ae2889749a48629be2501b0 # v1.9
        with:
          install: |
            LWP::UserAgent
            LWP::Simple
      - run: perl bin/gen_wctrans
      - run: perl Makefile.PL
      - run: make test TEST_VERBOSE=1 2>&1 | tee make.log
        # continue-on-error: true
      - name: Upload Failure
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: failure()
        with:
          name: artifacts
          path: .
